### ISSUE TITLE
机器人启动报错

### ISSUE THREAD

**Issue by GoldThree** [yokonsan/midjourney-api#12]
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('31.13.88.169', 443)]

看报错应该是连接不上，需要什么配置吗？

**Comment by GoldThree** [comment]
网络问题已解决

**Comment by 1615070057** [comment]
一样的问题, 请问最终是怎么解决的.

**Comment by 1615070057** [comment]
> 网络问题已解决

一样的问题, 请问最终是怎么解决的.

**Comment by tangmi1988** [comment]
同样的问题，怎么解决的？

**Comment by a1120235890** [comment]
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Task.__call__() done, defined at E:\炼数\midjourney-api-master\util\_queue.py:21> exception=MaxRetryError('超出最大重试次数')>
Traceback (most recent call last):
  File "E:\炼数\midjourney-api-master\util\_queue.py", line 22, in __call__
    await self.func(*self.args, **self.kwargs)
  File "E:\炼数\midjourney-api-master\lib\api\discord.py", line 138, in generate
    return await trigger(payload)
  File "E:\炼数\midjourney-api-master\lib\api\discord.py", line 33, in trigger
    return await fetch(session, TRIGGER_URL, data=json.dumps(payload))
  File "E:\炼数\midjourney-api-master\util\fetch.py", line 30, in connect_n_times
    raise MaxRetryError("超出最大重试次数")
exceptions.MaxRetryError: 超出最大重试次数

**Comment by momoyaoquaoao** [comment]
> 网络问题已解决

亲  你怎么解决的呀

**Comment by momoyaoquaoao** [comment]
> > 网络问题已解决
> 
> 亲 你怎么解决的呀

@yokonsan 大佬，我本地浏览器可以访问discord.com。
