### ISSUE TITLE
服务器执行python3 task_bot.py 时报异常了，参数都是按步骤操作填入的

### ISSUE THREAD

**Issue by tangmi1988** [yokonsan/midjourney-api#15]
Midjourney API拉下来后，按照步骤填入各种参数，但是启动时报错了。这个是啥原因？
错误信息：discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by yokonsan** [comment]
It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page.

**Comment by tangmi1988** [comment]
在bot页面，勾选上SERVER MEMBERS INTENT后，启动没有报错了
