### ISSUE TITLE
强烈建议支持多账号，多队列执行方案

### ISSUE THREAD

**Issue by skrleo** [yokonsan/midjourney-api#16]
我用于内部员工使用的 有时候会有多个员工使用，如果被占用了 那另外的员工只能等待完成之后才能使用 这不是很友好，

**Comment by yokonsan** [comment]
> 我用于内部员工使用的 有时候会有多个员工使用，如果被占用了 那另外的员工只能等待完成之后才能使用 这不是很友好，

上层业务做

**Comment by yokonsan** [comment]
#3 同样问题
