### ISSUE TITLE
关于图生图的使用上传接口返回的链接无法使用

### ISSUE THREAD

**Issue by augensternHe** [yokonsan/midjourney-api#19]
`{
  "message": "success",
  "upload_filename": "d8ae0b4a-0b8d-4a9a-8b55-e0033d294912/1125718076.jpg",
  "upload_url": "https://discord-attachments-uploads-prd.storage.googleapis.com/d8ae0b4a-0b8d-4a9a-8b55-e0033d294912/1125718076.jpg?upload_id=ADPycdu34ksNqZLXYt8QnkXS35_tgHsPUvmWKbS9UvUMfi11Ikz1y0hfkQ_IWnrfIz5UXbrvonwTPw9qZvO21WlMnERdMZ_4HBp4",
  "trigger_id": "1125718076"
}`
通过upload上传图片后处理其中所返回图片url再使用imagine生成时无法生成，并且将url复制到discord中生成时提示无法识别链接
![image](https://github.com/yokonsan/midjourney-api/assets/122500155/bbf1dea4-83a8-4ee6-bcba-a893e2d94d19)

**Comment by yokonsan** [comment]
> `{ "message": "success", "upload_filename": "d8ae0b4a-0b8d-4a9a-8b55-e0033d294912/1125718076.jpg", "upload_url": "https://discord-attachments-uploads-prd.storage.googleapis.com/d8ae0b4a-0b8d-4a9a-8b55-e0033d294912/1125718076.jpg?upload_id=ADPycdu34ksNqZLXYt8QnkXS35_tgHsPUvmWKbS9UvUMfi11Ikz1y0hfkQ_IWnrfIz5UXbrvonwTPw9qZvO21WlMnERdMZ_4HBp4", "trigger_id": "1125718076" }` 通过upload上传图片后处理其中所返回图片url再使用imagine生成时无法生成，并且将url复制到discord中生成时提示无法识别链接 ![image](https://user-images.githubusercontent.com/122500155/242842777-bbf1dea4-83a8-4ee6-bcba-a893e2d94d19.png)

多看看文档，图生图的链接不是用上传图片获得的链接

**Comment by wangrui00** [comment]
那是哪的链接？
