### ISSUE TITLE
/image调用一直失败

### ISSUE THREAD

**Issue by gustiness** [yokonsan/midjourney-api#20]
ct_n_times - 请求失败（ClientConnectorCertificateError），正在重试，剩余 0 次, Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]

请教下这个原因是什么那

**Comment by yokonsan** [comment]
本地网络能访问 discord 吗
相似 issue：#12
