### ISSUE TITLE
在阿里云服务器启动时，提示SSL错误

### ISSUE THREAD

**Issue by tangmi1988** [yokonsan/midjourney-api#25]
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

**Comment by yokonsan** [comment]
海外服务器吗，能正常访问 discord 吗

**Comment by skrleo** [comment]
> 海外服务器吗，能正常访问 discord 吗

我觉得 可以弄个代理，在国内也可以访问的那种

**Comment by tangmi1988** [comment]
> 海外服务器吗，能正常访问 discord 吗

香港服务器，可以正常ping通

**Comment by yokonsan** [comment]
> > 海外服务器吗，能正常访问 discord 吗
> 
> 香港服务器，可以正常ping通

看描述是证书验证不过，你可以试下在请求的时候加上`verify_ssl=False`。
在文件`util/fetch.py`第48行：

```python
...
    async with session.request(method, url, verify_ssl=False, **kwargs) as resp:
...
```

**Comment by tugers** [comment]
加了 verify_ssl=False 还是报错，有其他解决办法吗

**Comment by tugers** [comment]
File "D:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\ProgramData\Anaconda3\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]

**Comment by tugers** [comment]
用的是代理，能正常访问discord

**Comment by yokonsan** [comment]
参考：[https://stackoverflow.com/questions/63347818/aiohttp-client-exceptions-clientconnectorerror-cannot-connect-to-host-stackover](https://stackoverflow.com/questions/63347818/aiohttp-client-exceptions-clientconnectorerror-cannot-connect-to-host-stackover)

**Comment by Ghostlll** [comment]
遇到同样的问题，上面两个办法都解决不了呢。
  File "C:\Users\liulong\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\liulong\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]

**Comment by momoyaoquaoao** [comment]
> 遇到同样的问题，上面两个办法都解决不了呢。 File "C:\Users\liulong\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection transp, proto = await self._wrap_create_connection( File "C:\Users\liulong\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection raise client_error(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]

后来解决了吗
