### ISSUE TITLE
使用过程中会卡死请问是什么情况？

### ISSUE THREAD

**Issue by augensternHe** [yokonsan/midjourney-api#27]
图片生成接口无反应无回调，别的接口可以用，请问应该怎么处理？

**Comment by yokonsan** [comment]
可以看下 `http` 接口返回的内容，是否有提示：prompt 出现禁用词，或者其他错误信息

**Comment by augensternHe** [comment]
没有任何返回，discord那边也没有新消息

**Comment by yokonsan** [comment]
提问至少提供些日志信息，各个步骤调用截图吧

**Comment by zhylio** [comment]
prompt 出现禁用词会卡死导致后续正常词也不行了吗？
