### ISSUE TITLE
關於 imagine 的 value <# trigger_id #> 影響 圖生圖

### ISSUE THREAD

**Issue by jack206418070** [yokonsan/midjourney-api#28]
因為 imagine 的 prompt 在 prompt_handler() 當中被處理成
前頭會加上 <# trigger_id #>
導致 圖生圖的時候 midjourney 不能完整的判斷這個指令是圖生圖
以下是無法判斷的圖
<img width="820" alt="截圖 2023-06-05 下午4 27 50" src="https://github.com/yokonsan/midjourney-api/assets/44224865/3df72a9c-6851-4dd6-a1b8-90637db0033e">

這個是正常的判斷
<img width="844" alt="截圖 2023-06-05 下午4 27 54" src="https://github.com/yokonsan/midjourney-api/assets/44224865/c118633e-42dc-4362-bfec-2466f3c49b93">

如果自行拿掉 <# trigger_id #> 會造成什麼問題嗎?
目前測試 -> 一個人使用上並沒有什麼太大的問題
怕是不是有牽扯到列隊 callback 之類的判斷

另外感謝大神開源這個專案, 獻上 12 萬分敬意

**Comment by yokonsan** [comment]
这的确是个 bug，我今天修复下QAQ～
