### ISSUE TITLE
服务器一直收到请求404错误；NFO:     64.227.21.251:55514 - "POST /v1/api/trigger/bot HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by Fred3343** [yokonsan/midjourney-api#33]
NFO:     64.227.21.251:55514 - "POST /v1/api/trigger/bot HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52258 - "POST /v1/api/trigger/bot HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52260 - "POST /v1/api/trigger/bot HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52262 - "POST /v1/api/trigger/bot HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52264 - "POST /v1/api/trigger/bot HTTP/1.1" 404 Not Found

**Comment by yokonsan** [comment]
重复 issue #5
