### ISSUE TITLE
关于describe的问题

### ISSUE THREAD

**Issue by fanmaoyu0871** [yokonsan/midjourney-api#35]
你好，感谢分享！想问下，describe调用了命令，返回了4个描述，选择一个描述去生成图片，我看需要传入prompt，但是机器人这边哪里可以获取到这个prompt呢

**Comment by yokonsan** [comment]
> 你好，感谢分享！想问下，describe调用了命令，返回了4个描述，选择一个描述去生成图片，我看需要传入prompt，但是机器人这边哪里可以获取到这个prompt呢

不太明白你的意思，返回的 4 个描述就可以作为参考的 prompt 啊

**Comment by fanmaoyu0871** [comment]
现在我看机器人回调的message里面，没有这些prompt的信息，你可以看下不

**Comment by yokonsan** [comment]
没复现，请提供你调用方法和程序执行的日志

**Comment by fanmaoyu0871** [comment]
可以了，不好意思，他回调是在on_message_edit里，我没注意，感谢！
