### ISSUE TITLE
upscale调用的时候 midjouney 没有反应

### ISSUE THREAD

**Issue by GoldThree** [yokonsan/midjourney-api#36]
upscale 接口使用和 imagine 是一样的吗？为什么我调用的时候 discord页面都没有反应，但是 imagine 是没问题的，而且我手动 upscale 的时候生成的图片callback 也是收不到信息的？

**Comment by ffcloudy** [comment]
请问这个问题怎么解决的

**Comment by Anychnn** [comment]
这个有解决办法嘛，我看请求后返回结果不对 status=204,但是discord没有反应
