### ISSUE TITLE
运行task_bot报错，用的新加坡服务器

### ISSUE THREAD

**Issue by shudongW** [yokonsan/midjourney-api#37]
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by yokonsan** [comment]
重复 isuue：#15
