### ISSUE TITLE
之前有提到过的imagine接口无反应问题

### ISSUE THREAD

**Issue by augensternHe** [yokonsan/midjourney-api#39]
![image](https://github.com/yokonsan/midjourney-api/assets/122500155/f2b7ef07-9b46-4987-8526-5b1225f1aea2)
这是server运行报错，400之后再发请求就无反应了
![image](https://github.com/yokonsan/midjourney-api/assets/122500155/e36f508c-c888-448b-bbbd-da38407b6b83)
这是task_bot报错输出，也是无反应，请教一下是什么问题？

**Comment by yokonsan** [comment]
。。。
能不能先看看 README 再提问

**Comment by augensternHe** [comment]
跟README无关，是我的release地址端口填错了
