### ISSUE TITLE
🐛 回调地址怎么使用，有没有并发请求的限制

### ISSUE THREAD

**Issue by Mark0673** [yokonsan/midjourney-api#44]
### 问题简述

不是很明白回调地址的作用，另外怎么获取MJ生成的图片呢

### 复现方式

无

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by yokonsan** [comment]
重复 issue : #13

提交 issue 麻烦搜索下有没有重复问题， 先阅读 README 再提问
