### ISSUE TITLE
python task_bot.py运营报错问题

### ISSUE THREAD

**Issue by gaofeng2022** [yokonsan/midjourney-api#45]
报错主要有两个原因：1、无法连接discord，telnet discord.com 443，显示无法连接。解决办法：果断换梯子，可以试试https://steampp.net/。2、discord bot配置问题，打开https://discord.com/developers/applications，
![1686555173470](https://github.com/yokonsan/midjourney-api/assets/101937023/380d136b-928b-4186-b409-cffe95889960)，开启：SERVER MEMBERS INTENT 问题完美解决。

**Comment by gaofeng2022** [comment]
![1686555325764](https://github.com/yokonsan/midjourney-api/assets/101937023/cdeba94e-c902-4b19-9661-0c7ab0a81854)

**Comment by yokonsan** [comment]
MESSAGE CONTENT INTENT

是这个吧

**Comment by Andy-Ren** [comment]
通过这个api发的消息，会展现在 discord的频道中吗？

**Comment by panjiping** [comment]
我的还继续报错

**Comment by success110** [comment]
有解决方案了吗  按上面的尝试了   还是报错 
Cannot connect to host discord.com:443 ssl:default [Connection reset by peer]
