### ISSUE TITLE
callback_url 是你希望接收 midjourney 生成图片进度和结果的服务地址

### ISSUE THREAD

**Issue by gaofeng2022** [yokonsan/midjourney-api#46]
callback_url 是你希望接收 midjourney 生成图片进度和结果的服务地址
日志中是有输出图片链接的，确保配置的日志等级 `LOG_LEVEL` 为 `DEBUG` 或更低

_Originally posted by @yokonsan in https://github.com/yokonsan/midjourney-api/issues/13#issuecomment-1571749299_
这里说的日志等级是在哪里配置的？callback_url中接收的信息包格式是怎样的呢？

**Comment by yokonsan** [comment]
包格式见：https://github.com/yokonsan/midjourney-api/blob/master/task/bot/_typing.py
日志等级是在哪里配置：`.env` 文件中

**Comment by gaofeng2022** [comment]
写了一个callback api接口，post方式的，        
[HttpPost]
public async Task CallBackAsync([FromBody] dynamic CallBackData)，也配置到env文件中，但是没有被调用，不知道什么原因？有没有例子？

**Comment by gaofeng2022** [comment]
问题已经解决，是我配错了接口名称

**Comment by WellTung666** [comment]
> 写了一个callback api接口，post方式的， [HttpPost] public async Task CallBackAsync([FromBody] dynamic CallBackData)，也配置到env文件中，但是没有被调用，不知道什么原因？有没有例子？

请问要怎样接受返回的图片呢？

**Comment by makkarss929** [comment]
Hi @gaofeng2022  can u please send me your callback api interface as an example ? I would be very thankful to you. Thanks

**Comment by zailushang2006** [comment]
@gaofeng2022 你好，可以把回调的api的例子发给我吗？非常感谢

**Comment by neptunear** [comment]
怎么搞？

**Comment by neptunear** [comment]
> @gaofeng2022 你好，可以把回调的api的例子发给我吗？非常感谢

您知道怎么弄了吗

**Comment by CarterLsx** [comment]
CALLBACK_URL是https://discord.com/api/v9/interactions
