### ISSUE TITLE
🐛 服务启动后，调用接口，无任何数据返回

### ISSUE THREAD

**Issue by JankinHou** [yokonsan/midjourney-api#49]
### 问题简述

服务启动后没有报错，请求接口成功
{
  "message": "success",
  "trigger_id": "111111111",
  "trigger_type": "generate"
}

但是收不到callback的回调，discord的频道里也不提示，怎么知道请求是否成功呢

### 复现方式

已经按照教程来部署的

### 环境信息

-  OS: MacBook m2 
-  Python: Python 3.10.9
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by yokonsan** [comment]
看discord里 midjourney 有没有触发绘画任务

**Comment by JankinHou** [comment]
discord的频道里没有任何信息提示，也没有触发绘画任务。
task_bot.py服务已经打印了  on_ready  Logged in as xxx#1234
调用接口的命令是readme里的案例：
curl -X 'POST' \
  'http://127.0.0.1:8062/v1/api/trigger/imagine' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt": "a cute cat"
}'

请求接口后，返回如下
{"message":"success","trigger_id":"122332313","trigger_type":"generate"}

**Comment by JankinHou** [comment]
> discord的频道里没有任何信息提示，也没有触发绘画任务。 task_bot.py服务已经打印了 on_ready Logged in as xxx#1234 调用接口的命令是readme里的案例： curl -X 'POST' 'http://127.0.0.1:8062/v1/api/trigger/imagine' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{ "prompt": "a cute cat" }'
> 
> 请求接口后，返回如下 {"message":"success","trigger_id":"122332313","trigger_type":"generate"}

discord的频道里没有任何信息提示，也没有触发绘画任务。
task_bot.py服务已经打印了 on_ready Logged in as xxx#1234
调用接口的命令是readme里的案例：
curl -X 'POST'
'http://127.0.0.1:8062/v1/api/trigger/imagine'
-H 'accept: application/json'
-H 'Content-Type: application/json'
-d '{
"prompt": "a cute cat"
}'

请求接口后，返回如下
{"message":"success","trigger_id":"122332313","trigger_type":"generate"}

另外，我如果在discord频道里手动发送 绘图命令，task_bot.py能监听到绘画进度。

**Comment by yokonsan** [comment]
那就需要检查下频道ID是否配置对了，不是程序问题。close

**Comment by shlk20** [comment]
我今天也碰到了这个问题，各种配置均没变过，昨天晚上是正常运行的

**Comment by JankinHou** [comment]
> 我今天也碰到了这个问题，各种配置均没变过，昨天晚上是正常运行的

我用的VPN在本地。访问discord的也能通。就是收不到消息。 后来代码放到了一台海外的机器上，突然好了。 也不知道是不是网络的原因。

**Comment by shlk20** [comment]
> > 我今天也碰到了这个问题，各种配置均没变过，昨天晚上是正常运行的
> 
> 我用的VPN在本地。访问discord的也能通。就是收不到消息。 后来代码放到了一台海外的机器上，突然好了。 也不知道是不是网络的原因。

我刚放到了海外机器上，还是收不到消息，奇怪

**Comment by yokonsan** [comment]
今天discord报文改版了，我中午更新下

**Comment by shlk20** [comment]
> 今天discord报文改版了，我中午更新下

作者辛苦了 ☕️
