### ISSUE TITLE
/v1/api/trigger/bot报错

### ISSUE THREAD

**Issue by augensternHe** [yokonsan/midjourney-api#5]
请问/v1/api/trigger/bot接口是移除了吗，swagger接口里面没有，然后测试也提示找不到接口，使用imagine接口没有触发task_bot.py的内容好像。

**Comment by yokonsan** [comment]
> 请问/v1/api/trigger/bot接口是移除了吗，swagger接口里面没有，然后测试也提示找不到接口，使用imagine接口没有触发task_bot.py的内容好像。

这个接口移除了，根据功能拆开了
task_bot启动成功了吗，discord里面有生成画图任务吗

**Comment by skrleo** [comment]
> > 请问/v1/api/trigger/bot接口是移除了吗，swagger接口里面没有，然后测试也提示找不到接口，使用imagine接口没有触发task_bot.py的内容好像。
> 
> 这个接口移除了，根据功能拆开了 task_bot启动成功了吗，discord里面有生成画图任务吗

我觉得你这个非常不错，如果能把那个验证处理好就非常到位了

**Comment by augensternHe** [comment]
不好意思，因为我之前那个账号权限没开通，所以监听函数没有回调结果，开通之后已经一切正常了，代码功能非常棒，谢谢。另外还有一个问题，请问后续有图生图的开发计划吗？

>

**Comment by augensternHe** [comment]
> > 请问/v1/api/trigger/bot接口是移除了吗，swagger接口里面没有，然后测试也提示找不到接口，使用imagine接口没有触发task_bot.py的内容好像。
> 
> 这个接口移除了，根据功能拆开了 task_bot启动成功了吗，discord里面有生成画图任务吗

不好意思，因为我之前那个账号权限没开通，所以监听函数没有回调结果，开通之后已经一切正常了，代码功能非常棒，谢谢。另外还有一个问题，请问后续有图生图的开发计划吗？

**Comment by yokonsan** [comment]
> > > 请问/v1/api/trigger/bot接口是移除了吗，swagger接口里面没有，然后测试也提示找不到接口，使用imagine接口没有触发task_bot.py的内容好像。
> > 
> > 
> > 这个接口移除了，根据功能拆开了 task_bot启动成功了吗，discord里面有生成画图任务吗
> 
> 不好意思，因为我之前那个账号权限没开通，所以监听函数没有回调结果，开通之后已经一切正常了，代码功能非常棒，谢谢。另外还有一个问题，请问后续有图生图的开发计划吗？

在自测，近期上

**Comment by yokonsan** [comment]
图生文添加了
图生图我理解是 prompt：图片地址 + prompt，我可以加个上传图片获取图片消息地址的接口
