### ISSUE TITLE
🐛 调用u 命令不生效

### ISSUE THREAD

**Issue by cationCatM** [yokonsan/midjourney-api#50]
### 问题简述

![image](https://github.com/yokonsan/midjourney-api/assets/136546051/25de2d7b-483e-4e4b-94db-3cc2d22d2129)
![image](https://github.com/yokonsan/midjourney-api/assets/136546051/e253f26e-510f-450f-bae3-9d604fe21227)

discord那边没有发送消息，我的参数不对吗？

### 复现方式

![image](https://github.com/yokonsan/midjourney-api/assets/136546051/fd0571aa-317b-49c0-8379-e1cb8c2c4bf4)

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by yokonsan** [comment]
有 server 的日志吗。重启服务是否仍存在
