### ISSUE TITLE
🐛 INTERACTION_APPLICATION_COMMAND_INVALID_VERSION错误怎么解

### ISSUE THREAD

**Issue by getidone** [yokonsan/midjourney-api#51]
### 问题简述

今天调用文生图Api的时候，突然不行了，返回400错误。把错误信息详细看了一下：
{"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION", "message": "\u8be5\u6743\u9650\u5df2\u8fc7\u65f6\uff0c\u8bf7\u7a0d\u5019\u51e0\u5206\u949f\u518d\u8bd5"}]}}, "message": "Invalid Form Body"}

是因为"该权限已过时，请稍候几分钟再试"，是啥子原因？

### 复现方式

突然出现

### 环境信息

ubuntu-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by yokonsan** [comment]
discord 更新了报文结构，更新下代码

**Comment by getidone** [comment]
> discord 更新了报文结构，更新下代码

多谢回复，我自己做了一些本地更改，请问下核心更新的是哪个文件，我可能需要手动合并

**Comment by yokonsan** [comment]
自己看一下 commit 记录都不愿意吗？
