### ISSUE TITLE
🐛 发送指令都是成功的，就是收不到回调消息，另外发送了指令之后 discord 频道中会不会出现消息喃，我一直没有看到出现

### ISSUE THREAD

**Issue by Andy-Ren** [yokonsan/midjourney-api#54]
### 问题简述

🐛 发送指令都是成功的，就是收不到回调消息，另外发送了指令之后 discord 频道中会不会出现消息喃，我一直没有看到出现

### 复现方式

必现

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by Andy-Ren** [comment]
![image](https://github.com/yokonsan/midjourney-api/assets/1499402/aea41b85-322d-4ff9-8ec5-0ea62a821252)
发送绘画指令都是成功的，但是看不到discord上又消息，也收不到回调消息

**Comment by yokonsan** [comment]
更新下代码
