### ISSUE TITLE
重新登录了discord，也更新了user token，但消息传不过去了

### ISSUE THREAD

**Issue by HaiTao1983** [yokonsan/midjourney-api#55]
### 问题简述

您好，作者，之前调试成功了，discord也收到了绘画指令。但是，昨天重新登录了discord，然后我更新了USER_TOKEN，就出问题了，消息传不过去🐛 

### 复现方式

我也重新启动了云服务器，试了各种重启，依旧不成功，不知道问题出现在哪儿

### 环境信息

-  OS: 操作系统类型及其版本号: debian
-  Python: Python 版本号 (`python --version`) 3.9.2
-  Others: 其它信息

### 额外信息

![image](https://github.com/yokonsan/midjourney-api/assets/136770041/b594b70c-076d-4105-a1b7-35ac2a0ef5e9)

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by yokonsan** [comment]
discord 报文改版了，拉去最新代码

**Comment by HaiTao1983** [comment]
谢谢yokonsan，更新了midjourney部署，解决了，感谢回复
