### ISSUE TITLE
🐛 callback api接口有没有示例

### ISSUE THREAD

**Issue by yimengqiangu** [yokonsan/midjourney-api#59]
### 问题简述

我配置CALLBACK_URL=http://127.0.0.1:8000/callback，它没有被调用
from fastapi import FastAPI
from typing import List, TypedDict

app = FastAPI()

class Attachment(TypedDict):
    id: int
    url: str
    proxy_url: str
    filename: str
    content_type: str
    width: int
    height: int
    size: int
    ephemeral: bool

class EmbedsImage(TypedDict):
    url: str
    proxy_url: str

class Embed(TypedDict):
    type: str
    description: str
    image: EmbedsImage

class CallbackData(TypedDict):
    type: str
    id: int
    content: str
    attachments: List[Attachment]
    embeds: List[Embed]
    trigger_id: str

@app.post("/callback")
async def callback(callback_data: CallbackData):
    # 在这里可以访问解析后的参数
    # callback_data.type
    # callback_data.id
    # callback_data.content
    # callback_data.attachments
    # callback_data.embeds
    # callback_data.trigger_id

    # 在这里进行处理和逻辑操作

    return {"message": "Callback received"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

### 复现方式

执行以上代码

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by liuyuaaa** [comment]
解决了吗，问下怎么操作的
