### ISSUE TITLE
【bug report】 ImportError: cannot import name 'ParamSpec' from 'typing'

### ISSUE THREAD

**Issue by ramboLiang** [yokonsan/midjourney-api#69]
### 问题简述

python version = 3.9.13
os windows11
我通过命令行的方式启动 python server.py 
控制台抛出了一个错误，如下图所示
![image](https://github.com/yokonsan/midjourney-api/assets/105616022/e1351066-8534-4373-b3b1-81b43b9ab2a2)
问题代码如下
![image](https://github.com/yokonsan/midjourney-api/assets/105616022/71dc5452-36f8-401c-b238-73883f386e95)

### 复现方式

1、git clone 当前项目
2、使用python -m venv .venv
3、激活虚拟环境 .\.venv\Scripts\activate
4、pip install -r requirements.txt
5、python server.py
之后会报错

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 额外信息

我不知道是我python版本的问题还是,我把utils的_queue.py做了一些调整之后可以成功运行起来
![image](https://github.com/yokonsan/midjourney-api/assets/105616022/ec6e10c2-98be-4c7a-b82a-60e9c00c1d73)

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by huangbo-bo** [comment]
遇到同样的问题， 求解

**Comment by ramboLiang** [comment]
> 遇到同样的问题， 求解

我上面贴了解决方案了  你看一下

**Comment by chuyaguo2014** [comment]
@ramboLiang 我试了你的解决办法！成功了！谢谢你！

```python
from typing import Callable, Any, Dict, List
from typing_extensions import ParamSpec, Deque
```

(以后如果有朋友需要直接复制黏贴的，可以用^）
