### ISSUE TITLE
本地vpn调试，请求超时(超过最大重试次数)问题

### ISSUE THREAD

**Issue by ramboLiang** [yokonsan/midjourney-api#70]
### 问题简述

如果其他朋友跟我一样，在**本地**运行起来之后访问接口，一直出现请求超时得问题，如下图所示
![image](https://github.com/yokonsan/midjourney-api/assets/105616022/8565d4de-aed9-46b4-9d26-09aee7a15282)

### 复现方式

无

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  Others: 其它信息

### 额外信息

请修改如下代码，增加一个参数作为本地vpn得请求代理即可成功
![image](https://github.com/yokonsan/midjourney-api/assets/105616022/2cd51ccf-8353-48c9-811d-176c26ea0aa3)

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by taoxifa** [comment]
请问下你解决了吗？
