### ISSUE TITLE
🐛 运行一段时间后便无法响应

### ISSUE THREAD

**Issue by JankinHou** [yokonsan/midjourney-api#89]
### 问题简述

请问大家有没有遇到过，程序运行一段时间后，就无法正常实现绘图，mj-server容器日志显示有绘图请求，但是discord里不显示触发。mj-bot也没有回调的记录。往往需要重启才能解决。

### 复现方式

运行一段时间后会出现

### 环境信息

-  OS: centos8
-  Python: Python 3.10.6
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by ljjy1** [comment]
@JankinHou 试试我写的这个springboot中间件 支持多账号切换 提高了并发 支持代理 https://github.com/ljjy1/discord-mj-java

**Comment by 31702160136** [comment]
触发mj的敏感词后，队列会一直占用不会释放

**Comment by JankinHou** [comment]
> 触发mj的敏感词后，队列会一直占用不会释放

应该不是敏感词。我还在测试阶段，一天偶尔测几次，并没有什么敏感词啊

**Comment by 31702160136** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JankinHou** [comment]
> 触发mj的敏感词后，队列会一直占用不会释放
