### ISSUE TITLE
关于局部重绘的一些想法🐛 

### ISSUE THREAD

**Issue by 15899885850** [yokonsan/midjourney-api#90]
### 问题简述

大佬你好，最近刚开始使用你的项目，发现还没有实现局部重绘的接口，有一些想法想要分享一下。
之前我是使用selenium的库，进行鼠标的模拟操作，在实现局部重绘的时候，是通过上传一张图片，然后进行图像对比得到重绘区域的坐标，然后进行鼠标的拖拽后上传的。
不知道dc的机器人能不能实现类似的功能？
如果需要的话，我可以将我使用selenium进行局部重绘的代码进行分享。

### 复现方式

如上

### 环境信息

如上

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by vvhr** [comment]
注意看完成重绘的接口submit-job, 不需要你模拟上传图片, 只需要接口传入mask, mask就是对原图片进行黑白色处理, 白色为重绘区域, 黑色为保留区域, 将图片操作后转base64传给mask参数, 请求submit-job接口即可完成重绘. 不过submit-job要求必须传入custom_id,这个custom_id指的是用户点开对话框时产生的实例ID.这个需要监听浏览器才能获取到.
