### ISSUE TITLE
🐛Stopped working after the last midjourney update, are there any solutions

### ISSUE THREAD

**Issue by taimast** [yokonsan/midjourney-api#92]
### 问题简述

Stopped working after the last midjourney update, are there any solutions

### 复现方式

Start docker

### 环境信息

The api request is sent, but the result is not transmitted back through the bot

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by matthias33890** [comment]
I have the same Issue

**Comment by dogewo** [comment]
同，发送了imagine请求但是收不到回调，没有报错信息

**Comment by taimast** [comment]
Worked after last update

**Comment by taimast** [comment]
Worked after last update

**Comment by twinsant** [comment]
今天把它修复了：

https://github.com/yokonsan/midjourney-api/compare/master...twinsant:midjourney-api:master

顺便增加了代理配置
