### ISSUE TITLE
调用文生图没收到回调信息

### ISSUE THREAD

**Issue by lindeqian1994** [yokonsan/midjourney-api#96]
### 问题简述

INFO:     113.215.99.44:53941 - "POST /v1/api/trigger/imagine HTTP/1.1" 200 OK
2023-11-23 16:41:40 | DEBUG | 19926-140367270946624 | "/www/wwwroot/mjapi/midjourney-api/util/fetch.py:47":fetch - Fetch: https://discord.com/api/v9/interactions, {'data': '{"type": 2, "application_id": "XXX", "guild_id": "XXX", "channel_id": "XXX", "session_id": "XXX", "data": {"version": "1166847114203123795", "id": "XXX", "name": "imagine", "type": 1, "options": [{"type": 3, "name": "prompt", "value": "<#XXX#>a cute cat"}], "attachments": []}}'}

### 复现方式

接口文档测试  promot  {
  "prompt": "a cute cat"
} 

### 环境信息

-  OS: centos8
-  Python: 3.9.6
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yokonsan/midjourney-api)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是项目本身的问题
- [X] 本 issue 在 [issues](https://github.com/yokonsan/midjourney-api/issues) 中并没有重复问题

**Comment by lindeqian1994** [comment]
fetch.py 打印出来的结果   2023-11-23 17:20:30 | DEBUG | 24493-140549848323904 | "/www/wwwroot/mjapi/midjourney-api/util/fetch.py:50":fetch - 10086:<ClientResponse(https://discord.com/api/v9/interactions) [400 Bad Request]>
<CIMultiDictProxy('Date': 'Thu, 23 Nov 2023 09:20:30 GMT', 'Content-Type': 'application/json', 'Content-Length': '54', 'Connection': 'keep-alive', 'Set-Cookie': '__dcfduid=8bc8f6a489e111ee9eb8cecf5dc1a11f; Expires=Tue, 21-Nov-2028 09:20:30 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=86400', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=oLPwmuy7rBm1IvHAUYSbkk86nUtYPeKwXnm3Zu0PD5CdtjPHohj9u1J0%2FvR91TRWdZMKGyHjJg7ifptyxHI%2BkdFqXFC%2FaVcV9L1gbD1p0kcFRiARFl5xYI56uS9z"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "frame-ancestors 'none'; default-src 'none'", 'Set-Cookie': '__sdcfduid=8bc8f6a489e111ee9eb8cecf5dc1a11f4a520993ee33efd5532b1502a84e79b50b19f22176d318f21062131bdef3f152; Expires=Tue, 21-Nov-2028 09:20:30 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/', 'Set-Cookie': '__cfruid=166cdb1a433ca951ca5bbc18c8440211057b5e52-1700731230; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None', 'Set-Cookie': '_cfuvid=jhUEzWj8IMyZnLuTvDGFW2mZ6e1p3aO5sm2qLP6hIJg-1700731230193-0-604800000; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '82a8562acd240970-HKG')>

**Comment by lindeqian1994** [comment]
@yokonsan

**Comment by aiup2u** [comment]
我和你一样的错误。。。fetch - <ClientResponse(https://discord.com/api/v9/interactions) [400 Bad Request]> 咋解决的？
@lindeqian1994 @yokonsan

**Comment by stingoChen** [comment]
@aiup2u 请问你解决了嘛

**Comment by yuweb** [comment]
解决了吗
